feat: Enhance makim smoke tests for swarm

diff --git a/.makim.yaml b/.makim.yaml
--- a/.makim.yaml
+++ b/.makim.yaml
@@ -193,33 +193,74 @@ groups:
         help: Run smoke tests for swarm commands
         hooks:
           pre-run:
-            - task: docker.killall
+            # - task: docker.killall
+            - task: docker.leave_node
         env:
           SUGAR_FLAGS: --verbose --profile profile1
         run: |
           # Initialize swarm
-          sugar ${{ vars.SUGAR_FLAGS }} swarm init --options --advertise-addr 127.0.0.1
+          sugar ${{ vars.SUGAR_FLAGS }} swarm init --options "--advertise-addr 127.0.0.1"
 
-          # Test basic swarm commands
-          sugar ${{ vars.SUGAR_FLAGS }} ls
 
-          # Test service commands
-          # Still below commands are in experimental stage
-          # sugar ${{ vars.SUGAR_FLAGS }} create --service my-nginx --options --name my-web nginx:latest
-          # sugar ${{ vars.SUGAR_FLAGS }} ls
-          # sugar ${{ vars.SUGAR_FLAGS }} inspect --services my-web
-          # sugar ${{ vars.SUGAR_FLAGS }} ps --services my-web
-          # sugar ${{ vars.SUGAR_FLAGS }} scale --services my-web --options my-web=2
-          # sugar ${{ vars.SUGAR_FLAGS }} update --services my-web --options --replicas 1
+          # Test stack commands
+          echo $'\033[32mTesting stack deployment...\033[0m'
+          sugar ${{ vars.SUGAR_FLAGS }} swarm deploy --stack test-stack
+
+          # List services (with and without stack filter)
+          echo $'\033[32mTesting service listing...\033[0m'
+          sugar ${{ vars.SUGAR_FLAGS }} swarm ls
+          sugar ${{ vars.SUGAR_FLAGS }} swarm ls --stack test-stack
+
+          # Test stack ps command
+          echo $'\033[32mTesting stack ps command...\033[0m'
+          sugar ${{ vars.SUGAR_FLAGS }} swarm ps --stack test-stack
+
+          # Test service inspection
+          echo $'\033[32mTesting service inspection...\033[0m'
+          sugar ${{ vars.SUGAR_FLAGS }} swarm inspect --services service1-1 --stack test-stack
+
+          # Test service1-1 , service1-2 and service1-3 service three times ping
+          for port in 18000 18001 18002; do
+            for i in {1..3}; do
+              curl -s http://localhost:$port
+              echo $'\033[32m - Ping $i to port $port[0m'
+            done
+          done
+
+          # Test service logs (limited command to avoid test hanging)
+          echo $'\033[32mTesting service logs...\033[0m'
+          sugar ${{ vars.SUGAR_FLAGS }} swarm logs --services service1-1 --stack test-stack --tail 10
+          sugar ${{ vars.SUGAR_FLAGS }} swarm logs --services service1-2 --stack test-stack --tail 10
+
+
+          # Test service scaling
+          echo $'\033[32mTesting service scaling...\033[0m'
+          sugar ${{ vars.SUGAR_FLAGS }} swarm scale --stack test-stack --replicas service1-1=2,service1-2=3
+
+          # TODO : sugar swarm update is yet to be implemented and experimental stage
+          # Test service update
+          # echo "Testing service update..."
+          # sugar ${{ vars.SUGAR_FLAGS }} swarm update --services test-stack_service1-1 --replicas 1 --detach
+
+          # Test service rollback
+          echo $'\033[32mTesting service rollback specific services in a stack...\033[0m'
+          sugar ${{ vars.SUGAR_FLAGS }} swarm rollback --services service1-1,service1-3 --stack test-stack
+
+          # Test rollback with stack parameter
+          echo $'\033[32mTesting stack rollback all services in a stack...\033[0m'
+          sugar ${{ vars.SUGAR_FLAGS }} swarm rollback --stack test-stack --all
 
           # Test node commands
-          sugar ${{ vars.SUGAR_FLAGS }} node ls
-          NODE_ID=$(docker node ls --format "{{.ID}}" | head -n1)
-          sugar ${{ vars.SUGAR_FLAGS }} node inspect --options $NODE_ID
-          sugar ${{ vars.SUGAR_FLAGS }} node ps --options $NODE_ID
+          echo $'\033[32mTesting node commands...\033[0m'
+          sugar swarm node --ls
+          NODE_ID=$(docker node ls --format "{{.ID}}" )
+          echo $'\033[32mNode ID: $NODE_ID\033[0m'
+          sugar swarm node --inspect $NODE_ID
+          sugar swarm node --ps $NODE_ID
 
-          # Clean up services
-          sugar ${{ vars.SUGAR_FLAGS }} rm --services my-web
+          # Clean up services and stack
+          echo $'\033[32mCleaning up...\033[0m'
+          sugar ${{ vars.SUGAR_FLAGS }} swarm rm --stack test-stack
 
           # Leave swarm
           docker swarm leave --force
@@ -261,6 +302,9 @@ groups:
       killall:
         help: Kill all running Docker containers
         run: docker kill `docker ps -q` || true
+      leave_node:
+        help: Leave the swarm
+        run: docker node inspect self --format '{{.Spec.Role}}' &>/dev/null && { docker node leave --force && echo "Node left the swarm"; } || echo "Node already left the swarm"
 
   release:
     vars:
